"use strict";
/*
 * ATTENTION: The "eval" devtool has been used (maybe by default in mode: "development").
 * This devtool is neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
(self["webpackChunkascend"] = self["webpackChunkascend"] || []).push([["login7"],{

/***/ "./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js":
/*!***************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js ***!
  \***************************************************************************************************************************************************************************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! devextreme-vue/data-grid */ \"./node_modules/devextreme-vue/data-grid.js\");\n/* harmony import */ var devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var devextreme_data_data_source__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! devextreme/data/data_source */ \"./node_modules/devextreme/esm/data/data_source.js\");\n/* harmony import */ var devextreme_data_array_store__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! devextreme/data/array_store */ \"./node_modules/devextreme/esm/data/array_store.js\");\n\n\n\n/* harmony default export */ __webpack_exports__[\"default\"] = ({\n  components: {\n    DxDataGrid: devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0__.DxDataGrid,\n    DxColumn: devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0__.DxColumn,\n    DxEditing: devextreme_vue_data_grid__WEBPACK_IMPORTED_MODULE_0__.DxEditing\n  },\n  props: {\n    ID: {\n      type: Number,\n      default: () => 0\n    },\n    Data: {\n      type: Array,\n      default: () => []\n    },\n    DBName: {\n      type: String,\n      default: () => \"\"\n    },\n    PATH: {\n      type: String,\n      default: () => \"\"\n    },\n    templateData: {\n      type: Object,\n      default: () => {}\n    }\n  },\n  data() {\n    return {\n      APIHost: this.$appInfo.WebAPIHost,\n      userDS: null,\n      details: this.getDetails()\n    };\n  },\n  methods: {\n    getDetails() {\n      return new devextreme_data_data_source__WEBPACK_IMPORTED_MODULE_1__[\"default\"]({\n        store: new devextreme_data_array_store__WEBPACK_IMPORTED_MODULE_2__[\"default\"]({\n          data: this.templateData.data.TransactionDetails,\n          key: 'ID'\n        })\n      });\n    }\n  },\n  mounted() {\n    console.log(this.templateData.data.TransactionDetails);\n  }\n});\n\n//# sourceURL=webpack://ascend/./src/views/finance/cash-bank/cash-bank-detail.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B0%5D.use%5B0%5D");

/***/ }),

/***/ "./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0":
/*!*******************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0 ***!
  \*******************************************************************************************************************************************************************************************************************************************************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"render\": function() { return /* binding */ render; }\n/* harmony export */ });\n/* harmony import */ var vue__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! vue */ \"./node_modules/vue/dist/vue.runtime.esm-bundler.js\");\n\nfunction render(_ctx, _cache, $props, $setup, $data, $options) {\n  const _component_DxColumn = (0,vue__WEBPACK_IMPORTED_MODULE_0__.resolveComponent)(\"DxColumn\");\n  const _component_DxEditing = (0,vue__WEBPACK_IMPORTED_MODULE_0__.resolveComponent)(\"DxEditing\");\n  const _component_DxDataGrid = (0,vue__WEBPACK_IMPORTED_MODULE_0__.resolveComponent)(\"DxDataGrid\");\n  return (0,vue__WEBPACK_IMPORTED_MODULE_0__.openBlock)(), (0,vue__WEBPACK_IMPORTED_MODULE_0__.createBlock)(_component_DxDataGrid, {\n    \"data-source\": $data.details,\n    \"show-borders\": true\n  }, {\n    default: (0,vue__WEBPACK_IMPORTED_MODULE_0__.withCtx)(() => [(0,vue__WEBPACK_IMPORTED_MODULE_0__.createVNode)(_component_DxColumn, {\n      \"data-field\": \"TransactionDetailName\"\n    }), (0,vue__WEBPACK_IMPORTED_MODULE_0__.createVNode)(_component_DxColumn, {\n      \"data-field\": \"Amount\",\n      format: \"#,##0.##\"\n    }), (0,vue__WEBPACK_IMPORTED_MODULE_0__.createVNode)(_component_DxColumn, {\n      \"data-field\": \"Remarks\"\n    }), (0,vue__WEBPACK_IMPORTED_MODULE_0__.createVNode)(_component_DxEditing, {\n      \"allow-adding\": true,\n      \"allow-updating\": true,\n      \"allow-deleting\": true,\n      mode: \"row\"\n    })]),\n    _: 1 /* STABLE */\n  }, 8 /* PROPS */, [\"data-source\"]);\n}\n\n//# sourceURL=webpack://ascend/./src/views/finance/cash-bank/cash-bank-detail.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/vue-loader/dist/templateLoader.js??ruleSet%5B1%5D.rules%5B3%5D!./node_modules/vue-loader/dist/index.js??ruleSet%5B0%5D.use%5B0%5D");

/***/ }),

/***/ "./src/views/finance/cash-bank/cash-bank-detail.vue":
/*!**********************************************************!*\
  !*** ./src/views/finance/cash-bank/cash-bank-detail.vue ***!
  \**********************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _cash_bank_detail_vue_vue_type_template_id_79cc54a0__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./cash-bank-detail.vue?vue&type=template&id=79cc54a0 */ \"./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0\");\n/* harmony import */ var _cash_bank_detail_vue_vue_type_script_lang_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./cash-bank-detail.vue?vue&type=script&lang=js */ \"./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js\");\n/* harmony import */ var C_Files_Development_KilatService_Ascend_PreCheckACWeb_node_modules_vue_loader_dist_exportHelper_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./node_modules/vue-loader/dist/exportHelper.js */ \"./node_modules/vue-loader/dist/exportHelper.js\");\n\n\n\n\n;\nconst __exports__ = /*#__PURE__*/(0,C_Files_Development_KilatService_Ascend_PreCheckACWeb_node_modules_vue_loader_dist_exportHelper_js__WEBPACK_IMPORTED_MODULE_2__[\"default\"])(_cash_bank_detail_vue_vue_type_script_lang_js__WEBPACK_IMPORTED_MODULE_1__[\"default\"], [['render',_cash_bank_detail_vue_vue_type_template_id_79cc54a0__WEBPACK_IMPORTED_MODULE_0__.render],['__file',\"src/views/finance/cash-bank/cash-bank-detail.vue\"]])\n/* hot reload */\nif (false) {}\n\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (__exports__);\n\n//# sourceURL=webpack://ascend/./src/views/finance/cash-bank/cash-bank-detail.vue?");

/***/ }),

/***/ "./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js":
/*!**********************************************************************************!*\
  !*** ./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js ***!
  \**********************************************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"default\": function() { return /* reexport safe */ _node_modules_babel_loader_lib_index_js_clonedRuleSet_40_use_0_node_modules_vue_loader_dist_index_js_ruleSet_0_use_0_cash_bank_detail_vue_vue_type_script_lang_js__WEBPACK_IMPORTED_MODULE_0__[\"default\"]; }\n/* harmony export */ });\n/* harmony import */ var _node_modules_babel_loader_lib_index_js_clonedRuleSet_40_use_0_node_modules_vue_loader_dist_index_js_ruleSet_0_use_0_cash_bank_detail_vue_vue_type_script_lang_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../../../node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!../../../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./cash-bank-detail.vue?vue&type=script&lang=js */ \"./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=script&lang=js\");\n \n\n//# sourceURL=webpack://ascend/./src/views/finance/cash-bank/cash-bank-detail.vue?");

/***/ }),

/***/ "./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0":
/*!****************************************************************************************!*\
  !*** ./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0 ***!
  \****************************************************************************************/
/***/ (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {

eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"render\": function() { return /* reexport safe */ _node_modules_babel_loader_lib_index_js_clonedRuleSet_40_use_0_node_modules_vue_loader_dist_templateLoader_js_ruleSet_1_rules_3_node_modules_vue_loader_dist_index_js_ruleSet_0_use_0_cash_bank_detail_vue_vue_type_template_id_79cc54a0__WEBPACK_IMPORTED_MODULE_0__.render; }\n/* harmony export */ });\n/* harmony import */ var _node_modules_babel_loader_lib_index_js_clonedRuleSet_40_use_0_node_modules_vue_loader_dist_templateLoader_js_ruleSet_1_rules_3_node_modules_vue_loader_dist_index_js_ruleSet_0_use_0_cash_bank_detail_vue_vue_type_template_id_79cc54a0__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../../../node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!../../../../node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!../../../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./cash-bank-detail.vue?vue&type=template&id=79cc54a0 */ \"./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/finance/cash-bank/cash-bank-detail.vue?vue&type=template&id=79cc54a0\");\n\n\n//# sourceURL=webpack://ascend/./src/views/finance/cash-bank/cash-bank-detail.vue?");

/***/ })

}]);